name = "myfirstwebsite"
main = "worker.js"
compatibility_date = "2026-09-30"

[assets]
directory = "."

[[d1_databases]]
binding = "DB"
database_name = "forest-pop-scores"
database_id = "e1f131f7-c348-416e-ae78-ff2ab6f69e87"
